### ISSUE TITLE
Toast grid tree 사용시 setRow 문의

### ISSUE THREAD

**Issue by jkh1208** [nhnent/fe.application-grid#2064]
트리 그리드를 사용중이며, 그리드 외 input에 입력 받은 데이터를 버튼 클릭하여 그리드에 setRow를 해주고 싶은데 적용이 안되어 문의 드립니다. 스크립트 error 로그에는 grid.getRow(1)안에 _attributes: .. parentRowKey 관련한거 같은데 에러 로그는 아래와 같습니다.
Uncaught TypeError: Cannot read properties of undefined (reading 'parentRowKey')
    at makeObservable (constants.js:26:8)
    at Object.setRow (input.js:60:5)
    at Grid.dispatch (utils.js:69:8)
    at Grid.setRow (utils.js:69:8)
    at HTMLButtonElement.<anonymous> (tree.html:56:8)
    at HTMLButtonElement.dispatch (jquery-latest.min.js:3:8436)
    at r.handle (jquery-latest.min.js:3:5139)

트리그리드에서는 setRow를 지원하지 않는건지 아니면 다른 방법이 있다면 답변 부탁드리겠습니다.
아래는 제가 테스트 해본 샘플 코드입니다.
답변 부탁드리겠습니다.

<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
<link rel="stylesheet" href="https://uicdn.toast.com/grid/latest/tui-grid.css" />
<script src="https://uicdn.toast.com/grid/latest/tui-grid.js"></script>

<div id="grid"></div>
<br>
<input type="text" id="txt_tree"></input>
<button type="button" id="btn_tree">트리setRow 테스트</</button>

<script>
let testJson = {
	  name: ''
};

const grid = new tui.Grid({
      el: document.getElementById('grid'),
      data: [
			  {
				name: '최상위메뉴',
				_attributes: {
				  expanded: true // default: false
				},
				_children: [
				  {
					name: 'SET로우테스트 메뉴1'
				  },
				  {
					name: 'SET로우테스트 메뉴2'
				  }
				]
			  },			 
			],
      rowHeaders: ['checkbox'],
      bodyHeight: 500,
      treeColumnOptions: {
        name: 'name',
        useCascadingCheckbox: true
      },
      columns: [
        {
          header: 'Name',
          name: 'name',
          width: 300
        }
      ]
    });
	
	$('#btn_tree').click(() => {
	
		testJson.name = $('#txt_tree').val();
	
		grid.setRow(1, testJson);
	});	
</script>

**Comment by HIMZ5221** [comment]
선언하신 testJson 객체가 의도와다르게 얕은복사되었습니다.
전역변수가 아닌, 이벤트내에서 선언하여, 사용해보시길 바랍니다.

**Comment by HIMZ5221** [comment]
선언하신 testJson 객체가 의도와 다르게 얕은 복사되었습니다.
전역변수가 아닌, 이벤트 내에서 선언하여, 사용해 보시길 바랍니다.

tree에 setRow는 사용가능합니다.
